# -*- coding: utf-8 -*-
"""Probability

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z2yKHfqBzB-RRc83Icl6f28uXTju4Vry

Question no. 1 A die is rolled. What is the probability of getting:

(a) An even number

Answer: when the die is rolled the outcome is 6
(1,2,3,4,5,6)

The number of even number outcome is 3(2,4,6)

The probability of even number is 3/6 = 1/2

(b) A number greater than 4

Answer: when the die is rolled the outcome is 6(1,2,3,4,5,6)

The number greater than 4 outcome is 2(5,6)

The probability of a number greater than 4 is 2/6 = 1/3

Question no. 2 In a class of 50 students:

20 like mathematics(M)

15 like science (S)

5 like both subjects

What is the probability that a student chosen at random likes Mathematics or science?

A student chosen at random likes mathematics or science is 20+15-5 = 30

The probability is 30/50 = 3/5

Question no. 3 A bag has 3 red and 2 blue balls. if one ball is drawn randomly and is red, what is the probability that the next ball is also red(without replacement)?

The total ball remaining is 4 and in 2 ball is red and 2 ball is blue

Probability of red ball is 2/4 = 1/2

Question no. 4 The population of a school is divided into 60% boys and 40% girls. If you want equal representation of both genders in the sample, which method should you use: Simple Random Sampling or stratified Sampling?

Answer: Stratified Sampling because it ensures equal representation from both group.

Question no. 5 The average height of 1000 students = 160cm. A sample of 100 students shows an average height = 158cm.

find the sampling error.

Answer: Sampling error = 160-158 =2

Question no. 6 The population mean salary is rs50000 with Standard deviation(a) = 5000. if we take a sample of 100 employees, what is the standard error of the mean(SEM)?

Answer: Standard error of the mean = standard deviation/ underroot of sample size
        5000/10 = 500

Question no. 7 In a group of 100 students:
40 like Cricket (C)

30 like Football (F)

10 like both Cricket and Football

Find the probability that a student likes at least one sport

Answer: The probability of student like one sport = 40+30-10/100 = 0.6

Question no. 8 From a deck of 52 cards, two cards are drawn without replacement. What is the probability that both are Aces?

Answer: Total aces in 52 cards is 4

Probability first card is Ace = 4/52 = 1/13

Probability of second card is Ace = 3/51 = 1/17

 probability of both are aces = 1/13*1/17 = 1/221

Question no. 9 A factory produces bulbs with 2% defective rate. If 5 bulbs are chosen at random, what is the probability that all are non-defective?

Answer:Defective rate = 2%

Non-defective rate = 98%

probability of that all are non defective = (0.98)^5 = 0.90

Question no. 10 Differentiate between discrete and continuous random variable with example.

Answer: Discrete variable: In discrete variable the values are coutable, whole number.

example: No. of student, number of cars, number of heads in coin toss
Continous variable: In continous variable the value any value(decimal, integer), infinite value range

Example: Height, temperature, weight
"""



